from groq import Groq
from backend.config import GROQ_API_KEY, GROQ_MODEL, FRIDAY_PERSONA

client = Groq(api_key=GROQ_API_KEY)

# Per-session conversation store instead of one shared list.
# Key = session_id (a string generated by the frontend), Value = that session's message history.
conversations: dict[str, list] = {}

# Keep the system prompt plus the last N messages, so history doesn't grow forever.
MAX_HISTORY_MESSAGES = 20

from backend.rag import query_documents

def check_groq_health():
    if not GROQ_API_KEY:
        raise ValueError(f"CRITICAL ERROR: GROQ_API_KEY is not set in .env!")
    try:
        print("Checking Groq API Health...")
        client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": "ping"}],
            max_tokens=5
        )
        print("Groq API connected successfully.")
    except Exception as e:
        raise ConnectionError(f"CRITICAL ERROR: Failed to connect to Groq API. Please check your GROQ_API_KEY or connection. Details: {e}")

check_groq_health()

def _get_session(session_id: str) -> list:
    """Fetch this session's history, creating it fresh if it doesn't exist yet."""
    if session_id not in conversations:
        conversations[session_id] = [{"role": "system", "content": FRIDAY_PERSONA}]
    return conversations[session_id]

def _trim_history(history: list) -> list:
    """Keep the system prompt (always first) plus only the most recent messages."""
    if len(history) <= MAX_HISTORY_MESSAGES + 1:
        return history
    system_msg = history[0]
    recent = history[-MAX_HISTORY_MESSAGES:]
    return [system_msg] + recent

def ask_friday(user_text: str, session_id: str):
    history = _get_session(session_id)
    context = query_documents(user_text)

    if context:
        prompt_with_context = f"Context from documents:\n{context}\n\nUser says: {user_text}"
        history.append({"role": "user", "content": prompt_with_context})
    else:
        history.append({"role": "user", "content": user_text})

    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=history,
            max_tokens=150,
            temperature=0.7
        )
        reply = response.choices[0].message.content.strip()
    except Exception as e:
        reply = f"Having trouble reaching my brain, boss. {str(e)}"

    history.append({"role": "assistant", "content": reply})
    conversations[session_id] = _trim_history(history)
    return reply

def ask_friday_stream(user_text: str, session_id: str):
    history = _get_session(session_id)
    context = query_documents(user_text)

    if context:
        prompt_with_context = f"Context from documents:\n{context}\n\nUser says: {user_text}"
        history.append({"role": "user", "content": prompt_with_context})
    else:
        history.append({"role": "user", "content": user_text})

    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=history,
            max_tokens=150,
            temperature=0.7,
            stream=True
        )
        full_reply = ""
        for chunk in response:
            if getattr(chunk.choices[0].delta, "content", None):
                text = chunk.choices[0].delta.content
                full_reply += text
                yield f"data: {text}\n\n"

        history.append({"role": "assistant", "content": full_reply})
        conversations[session_id] = _trim_history(history)

    except Exception as e:
        yield f"data: Having trouble reaching my brain, boss. {str(e)}\n\n"